# Generated by Django 6.0.1 on 2026-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
