# Generated by Django 6.0.1 on 2026-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_product_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=500),
        ),
    ]
